name: Build Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Lint and format
        run: bun run ci

      - name: Build source files
        run: |
          bun run zip
          bun run zip:firefox

      - name: Find and upload Firefox artifact
        id: find_firefox_zip
        run: |
          firefox_file=$(ls .output/*-firefox.zip)
          echo "Uploading $firefox_file"
          echo "firefox_file=$firefox_file" >> $GITHUB_OUTPUT

      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v4
        with:
          name: live-folder-firefox
          path: ${{ steps.find_firefox_zip.outputs.firefox_file }}

      - name: Find and upload sources artifact
        id: find_sources_zip
        run: |
          sources_file=$(ls .output/*-sources.zip)
          echo "Uploading $sources_file"
          echo "sources_file=$sources_file" >> $GITHUB_OUTPUT

      - name: Upload sources artifact
        uses: actions/upload-artifact@v4
        with:
          name: live-folder-sources
          path: ${{ steps.find_sources_zip.outputs.sources_file }}

      - name: Find and upload Chrome artifact
        id: find_chrome_zip
        run: |
          chrome_file=$(ls .output/*-chrome.zip)
          echo "Uploading $chrome_file"
          echo "chrome_file=$chrome_file" >> $GITHUB_OUTPUT

      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v4
        with:
          name: live-folder-chrome
          path: ${{ steps.find_chrome_zip.outputs.chrome_file }}
